micropost:
  content_size: 140
  microposts_per_page: 10
  size_picture: 1
user:
  avatar_size: 50
  avatar_size_follow: 30
  maximum_name: 50
  maximum_email: 100
  minimum_password: 6
  users_per_page: 10
helper:
  avatar_size: 80
password:
  time_reset: 2
